spring:
  application:
    name: discovery-service

eureka:
  server:
    enableSelfPreservation: false   # Disable self-preservation mode for testing purposes
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 8761
