spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

  security:
    user:
      name: admin
      password: admin123

server:
  port: 8888
